apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
  labels:
    app: image
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: wtrep/image-repo-image:latest
          env:
            - name:
              value:
            - name:
              value:
            - name:
              value:
          ports:
            - containerPort: 8080