apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: repo.trep.cloud
      http:
        paths:
          - path: /
            backend:
              serviceName: