FROM golang:1.15.1

ENV GOPRIVATE=github.com/wtrep/image-repo-backend

WORKDIR /go/src/app

COPY auth ./auth
COPY common ./common
COPY main_auth.go .
COPY go.mod .
COPY go.sum .

RUN go get -v -d
RUN go install -v

CMD ["image-repo-backend"]


