apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env-vars
data:
  DB_USERNAME: backend-sa
  DB_NAME: shopify-image-db
  DB_CONNECTION_STRING: shopify-challenge-backend:us-east1:shopify-image-db=tcp:3306
  CLOUD_SQL_CREDENTIAL_FILE: /secrets/sql-sa.json
  BUCKET: shopify-challenge-image-bucket
  BUCKET_URL_SIGNING_KEY: /opt/certs/bucket-sa.json