apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-microservice-deployment
  labels:
    app: shopify-backend-challenge-image
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopify-backend-challenge-image
  template:
    metadata:
      labels:
        app: shopify-backend-challenge-image
    spec:
      containers:
        - name: image-microservice
          image: wtrep/shopify-backend-challenge-image:1.0.3
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: gcp-sa-volume
              mountPath: /opt/certs
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-env-vars
                  key: DB_USERNAME
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-env-vars
                  key: DB_NAME
            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  name: backend-env-vars
                  key: BUCKET
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  name: backend-env-vars
                  key: GOOGLE_APPLICATION_CREDENTIALS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-password
                  key: DB_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key
                  key: JWT_KEY
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=shopify-image-repo:northamerica-northeast1:shopify-challenge-images-repo-3=tcp:3306"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: sql-secret-mount
              mountPath: /secrets/
              readOnly: true
      volumes:
        - name: sql-secret-mount
          secret:
            secretName: sql-sa-secret
        - name: gcp-sa-volume
          secret:
            secretName: gcp-image-sa